model:
  file_path: "models/500e.trt"
  label_list: ['enemy','down','friend']
  enemy_list: ['enemy','down']
  conf: 0.35

mouse:
  aimbot_button: left
  switch_button: x2
  silent_button: alt_gr
  silent_aim: caps_lock

  max_lock_dis: 100
  max_step_dis: 30
  max_pid_dis: 50
  pos_factor: 0.02
  pidx_kp: 3.65  #1.12
  pidx_kd: 3.54 #3.51
  pidx_ki: 0

  pidy_kp: 1.22
  pidy_kd: 0.24   
  pidy_ki: 0.0

  smooth: 0.8
  mag: 2
  serial_port: "COM3"

resolution_x: 1920
resolution_y: 1080
camera: "dxcam" # Change this option to 'mss' for better performance on low refresh rate monitors. 
fix_dxcam_error_hook: False # maye Have an issus
fix_dxcam_thread_join: False

debug: True # Works well with UI
log_level: "info" # Options: debug, info, warning, error, Only works when running in no-GUI mode

auto_update: True
